"""finished 1

Revision ID: 02d67ac7a8b1
Revises: 666c9ff81a52
Create Date: 2024-07-29 20:43:36.701229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d67ac7a8b1'
down_revision: Union[str, None] = '666c9ff81a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_id')
    # ### end Alembic commands ###



