"""finished 3

Revision ID: 104aec26f3d3
Revises: 02d67ac7a8b1
Create Date: 2024-07-30 10:11:14.829099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104aec26f3d3'
down_revision: Union[str, None] = '02d67ac7a8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_id')
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
    
#     # ### end Alembic commands ###
