"""Product model adde ovreall price field

Revision ID: 1b9cb5938e63
Revises: 1548e03df36d
Create Date: 2024-06-23 15:35:09.134179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9cb5938e63'
down_revision: Union[str, None] = '1548e03df36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('overall_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'overall_price')
    # ### end Alembic commands ###
