"""Column type added

Revision ID: 2bd2b83d3e43
Revises: 6a7f75432ce4
Create Date: 2024-06-23 16:13:52.580049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd2b83d3e43'
down_revision: Union[str, None] = '6a7f75432ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('expiry_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'expiry_date')
    # ### end Alembic commands ###
