"""model field changed

Revision ID: 47666e5eaa01
Revises: 4a1ebd9f6a6d
Create Date: 2024-07-26 15:30:07.480284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47666e5eaa01'
down_revision: Union[str, None] = '4a1ebd9f6a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add a new column with the desired type
    op.add_column('sale', sa.Column('amount_float', sa.Float(), nullable=True))
    
    # Step 2: Copy data from the old column to the new column
    op.execute('UPDATE sale SET amount_float = amount')
    
    # Step 3: Drop the old column
    op.drop_column('sale', 'amount')
    
    # Step 4: Rename the new column to the old column's name
    op.alter_column('sale', 'amount_float', new_column_name='amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the old column back
    op.add_column('sale', sa.Column('amount_integer', sa.INTEGER(), nullable=True))
    
    # Step 2: Copy data from the new column to the old column
    op.execute('UPDATE sale SET amount_integer = amount')
    
    # Step 3: Drop the new column
    op.drop_column('sale', 'amount')
    
    # Step 4: Rename the old column back to the original name
    op.alter_column('sale', 'amount_integer', new_column_name='amount')
    # ### end Alembic commands ###
