"""overall sale field added to sale-time

Revision ID: 4a1ebd9f6a6d
Revises: f481e3536318
Create Date: 2024-07-14 18:22:54.361412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1ebd9f6a6d'
down_revision: Union[str, None] = 'f481e3536318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('overall_for_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'overall_for_sale')
    # ### end Alembic commands ###
