"""qr_code_colum aded

Revision ID: 765ae28918e7
Revises: 83eee73482d7
Create Date: 2024-07-04 20:28:57.416738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765ae28918e7'
down_revision: Union[str, None] = '83eee73482d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_cards', sa.Column('qr_code_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount_cards', 'qr_code_image')
    # ### end Alembic commands ###
