"""add discount

Revision ID: 7d5a45fc85b2
Revises: bc702347ae2c
Create Date: 2024-06-22 08:36:42.507478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5a45fc85b2'
down_revision: Union[str, None] = 'bc702347ae2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sale', sa.Column('discount', sa.Float(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('sale', 'discount')
    pass
    # ### end Alembic commands ###
