"""discount card model added

Revision ID: 83eee73482d7
Revises: 
Create Date: 2024-07-04 15:50:58.425314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83eee73482d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_cards', sa.Column('name', sa.String(), nullable=True))
    op.add_column('discount_cards', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('discount_cards', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount_cards', 'date_added')
    op.drop_column('discount_cards', 'surname')
    op.drop_column('discount_cards', 'name')
    # ### end Alembic commands ###
