"""Add cash, debt, and card columns to Sale model

Revision ID: bc702347ae2c
Revises: 372a9ceac0ec
Create Date: 2024-06-22 08:30:23.705916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc702347ae2c'
down_revision: Union[str, None] = '372a9ceac0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('cash', sa.Float(), nullable=True))
    op.add_column('sale', sa.Column('debt', sa.Float(), nullable=True))
    op.add_column('sale', sa.Column('card', sa.Float(), nullable=True))
    op.drop_column('sale', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('payment_type', sa.VARCHAR(), nullable=True))
    op.drop_column('sale', 'card')
    op.drop_column('sale', 'debt')
    op.drop_column('sale', 'cash')
    # ### end Alembic commands ###
