"""product model changed

Revision ID: c4026d5ce9c7
Revises: 99029da4abd2
Create Date: 2024-08-17 10:32:31.332511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4026d5ce9c7'
down_revision: Union[str, None] = '99029da4abd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('boxes_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'boxes_left')
    # ### end Alembic commands ###
