"""data added field is added to userExpances

Revision ID: ca0e9bc86533
Revises: 37b28e613846
Create Date: 2024-06-19 16:06:58.038188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database_config.database_conf import current_time

# revision identifiers, used by Alembic.
revision: str = 'ca0e9bc86533'
down_revision: Union[str, None] = '37b28e613846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('user_expances', sa.Column('date_added', sa.DateTime, default=current_time))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_expances', 'date_added')
    # ### end Alembic commands ###
