"""products model added

Revision ID: f481e3536318
Revises: 765ae28918e7
Create Date: 2024-07-13 15:44:53.507898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f481e3536318'
down_revision: Union[str, None] = '765ae28918e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('boxes_left', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('packages_left', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('units_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'units_left')
    op.drop_column('products', 'packages_left')
    op.drop_column('products', 'boxes_left')
    # ### end Alembic commands ###
